- name: Ensure pre-reqs for docker_container module
  hosts: localhost
  tasks:
  - pip: name=docker state=present

- name: Ensure docker containers created
  hosts: localhost
  tasks:
  - name: Ensure docker container started
    docker_container:
      image: python
      interactive: yes
      name: "{{ item }}"
      state: started
    loop: "{{ query('inventory_hostnames', 'containers') }}"

- name: Ensure git configured in containers
  hosts: containers
  tasks:
  - git_config: scope=global list_all=yes
  - git_config: scope=global name=user.email value=annguyen281@gmail.com
  - git_config: scope=global name=user.name value=Nguyen
  - git_config: scope=global list_all=yes